spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/goods
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml

server:
    port: 8080

debug: true
trace: false

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR         # 日志不打印条件评估报告